[project]
name = "noetic-search-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygobject>=3.50.0",
    "ruff>=0.9.4",
]
