name: Publish Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
      
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.uv/bin" >> $GITHUB_PATH
      
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev libgirepository1.0-dev
      
    - name: Install dependencies with uv
      run: |
        uv add pyinstaller
      
    - name: Build executable
      run: |
        uv run pyinstaller main.py --onefile
      
    - name: Archive binary
      run: |
        mkdir -p release
        mv dist/main release/
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-binary
        path: release/main
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

