name: Ruff Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.uv/bin" >> $GITHUB_PATH

    - name: Install System Dependencies 
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev
        sudo apt-get install -y libgirepository1.0-dev
    
    - name: Install dependencies with uv
      run: |
        uv add ruff
    
    - name: Run Ruff
      run: |
        OUTPUT=$(uv run ruff check)
          echo "$OUTPUT"
          if [[ "$OUTPUT" != *"All checks passed!"* ]]; then
            echo "Linter Failure."
            exit 1
          fi
